### ISSUE TITLE
ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

### ISSUE THREAD

**Issue by ashutosh-kumar-x** [huggingface/text-generation-inference#1383]
### System Info

With 2XL40 I get shard-manager error for docker image text-generation-inference:1.0.2 and with parameters --model-id meta-llama/Llama-2-13b-chat-hf  --quantize bitsandbytes-nf4
**Please note on same HARDWARE (runpod) If I start with 1 L40 it works fine.**
Complete logs
===========================
2023-12-28T13:17:07.318695558Z You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
2023-12-28T13:17:07.318704498Z [E ProcessGroupNCCL.cpp:828] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, Timeout(ms)=60000) ran for 69662 milliseconds before timing out.
2023-12-28T13:17:07.318723495Z [E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
2023-12-28T13:17:07.318732015Z [E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
2023-12-28T13:17:07.318739139Z terminate called after throwing an instance of 'std::runtime_error'
2023-12-28T13:17:07.318746682Z   what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, Timeout(ms)=60000) ran for 69662 milliseconds before timing out. rank=0
2023-12-28T13:17:07.318753736Z 2023-12-28T13:17:07.318242Z ERROR shard-manager: text_generation_launcher: Shard process was signaled to shutdown with signal 6 rank=0
2023-12-28T13:17:07.412357080Z 2023-12-28T13:17:07.412131Z ERROR text_generation_launcher: Shard 0 failed to start
2023-12-28T13:17:07.412402547Z 2023-12-28T13:17:07.412169Z  INFO text_generation_launcher: Shutting down shards
2023-12-28T13:17:07.439809364Z 2023-12-28T13:17:07.439583Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=1
2023-12-28T13:17:07.439912939Z Error: ShardCannotStart
2023-12-28T13:17:19.420839552Z 2023-12-28T13:17:19.420619Z  INFO text_generation_launcher: Args { model_id: "meta-llama/Llama-2-13b-chat-hf", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(BitsandbytesNF4), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "2b2b2ab83317", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-12-28T13:17:19.420878384Z 2023-12-28T13:17:19.420665Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-12-28T13:17:19.420903876Z 2023-12-28T13:17:19.420842Z  INFO download: text_generation_launcher: Starting download process.
2023-12-28T13:17:22.499033233Z 2023-12-28T13:17:22.498819Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.
2023-12-28T13:17:22.499068712Z 
2023-12-28T13:17:23.026542263Z 2023-12-28T13:17:23.026351Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-12-28T13:17:23.026779794Z 2023-12-28T13:17:23.026663Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-12-28T13:17:23.026850683Z 2023-12-28T13:17:23.026779Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-12-28T13:17:33.040889105Z 2023-12-28T13:17:33.040556Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-12-28T13:17:33.041569849Z 2023-12-28T13:17:33.041350Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=1

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

rundpod
1XL40
exposed ports 80 and localhost
text_generation_launcher: Args { model_id: "meta-llama/Llama-2-13b-chat-hf", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(BitsandbytesNF4), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "2b2b2ab83317", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }

### Expected behavior

Launcher should work correctly ..

**Comment by ashutosh-kumar-x** [comment]
I noticed only port 80 was exposed to docker and i could in Args that port 29500 was also needed so I exposed port 29500 in my docker and it works now. 
2023-12-28T13:28:50.945141984Z 2023-12-28T13:28:50.944917Z  INFO text_generation_launcher: Sharding model on 2 processes

Is this correct analysis for it working this time with 2XL40.
