### ISSUE TITLE
Abnormally high GPU memory usage for c4ai-command-r-plus

### ISSUE THREAD

**Issue by heibaidaolx123** [huggingface/text-generation-inference#1769]
### System Info

tgi image: ghcr.io/huggingface/text-generation-inference:2.0

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Hi, I tried to run tgi 2.0 with cohere command-r-plus 104B.
I have a machine with 8*A30-24G, 196G device memory totally. I ran tgi with eetq, so the model params would take 104G. For kv, mem consumpstion can be caculated by `2 * sizeof(flaot16) * num_layers * num_kv_head * head_size * seq_len`, that's aournd 2.5G for 10k tokens. Theoretically, it's far from OOM.
But when running launcher with `--max-batch-prefill-tokens 10000` and `--max-input-length 10000`, the server threw  `CUDA out of memory` error when warmup.
The command:
```
docker run --rm $args \
 ghcr.io/huggingface/text-generation-inference:2.0 \
  --model-id /model \
  --max-concurrent-requests 2 \
  --max-batch-prefill-tokens 10000 \
  --max-input-length 10000 \
  --max-total-tokens 11000 \
  --num-shard $NUM_SHARD \
  --cuda-memory-fraction 0.99 \
  --cuda-graphs 0 \
  --quantize eetq \
  -p 8089
```
The error:
```
2024-04-19T11:06:25.868590Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 768, in warmup
    _, batch, _ = self.generate_token(batch)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 1052, in generate_token
    prefill_logprobs_tensor = torch.log_softmax(out, -1)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.77 GiB. GPU 4 has a total capacty of 23.49 GiB of which 3.99 GiB is free. Process 55623 has 19.49 GiB memory in use. Of the allocated memory 18.31 GiB is allocated by PyTorch, and 711.15 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

The above exception was the direct cause of the following exception:
......
```

### Expected behavior

serve normally

**Comment by heibaidaolx123** [comment]
It turns out that computing logprobs for prefilling when warmup consumed too much memory, and after turning it off, tgi serves normally as expected.

**Comment by maylorian** [comment]
Hi, I'm having the exact same problem. How did you manage to solve it?

**Comment by heibaidaolx123** [comment]
> Hi, I'm having the exact same problem. How did you manage to solve it?

Change prefill_logprobs to false [here](https://github.com/huggingface/text-generation-inference/blob/4c698fa6c2ea17ae3372b3d6b6971654817d1969/router/client/src/client.rs#L148), and use /generate api
