### ISSUE TITLE
Cannot load Vicuna-13B

### ISSUE THREAD

**Issue by SupreethRao99** [huggingface/text-generation-inference#260]
Hello,

@OlivierDehaene, @patrickvonplaten 

I'm running a server with 4xT4 16Gb, I would like to run distributed inference on all 4 of my GPU's, when I run 
```
docker run --gpus all --shm-size 1g -p 0.0.0.0:8000:80 -v /home/vicuna:/data ghcr.io/huggingface/text-generation-inference:latest --model-id /data/stable-vicuna-13b --num-shard 4
```
 I'm getting this as the error
```
2023-04-29T08:27:11.623013Z  INFO text_generation_launcher: Args { model_id: "/data/stable-vicuna-13b", revision: None, sharded: None, num_shard: Some(4), quantize: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1000, max_total_tokens: 1512, max_batch_size: None, waiting_served_ratio: 1.2, max_batch_total_tokens: 32000, max_waiting_tokens: 20, port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None }
2023-04-29T08:27:11.623037Z  INFO text_generation_launcher: Sharding model on 4 processes
2023-04-29T08:27:11.623590Z  INFO text_generation_launcher: Starting shard 0
2023-04-29T08:27:11.623727Z  INFO text_generation_launcher: Starting shard 1
2023-04-29T08:27:11.624071Z  INFO text_generation_launcher: Starting shard 3
2023-04-29T08:27:11.624164Z  INFO text_generation_launcher: Starting shard 2
2023-04-29T08:27:17.819514Z ERROR shard-manager: text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 58, in serve
    server.serve(model_id, revision, sharded, quantize, uds_path)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 155, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize))
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 124, in serve_inner
    model = get_model(model_id, revision, sharded, quantize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 133, in get_model
    return FlashLlamaSharded(model_id, revision, quantize=quantize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 187, in __init__
    self.model = model.eval().to(device)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
 rank=3
2023-04-29T08:27:17.819555Z ERROR shard-manager: text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 58, in serve
    server.serve(model_id, revision, sharded, quantize, uds_path)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 155, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize))
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 124, in serve_inner
    model = get_model(model_id, revision, sharded, quantize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 133, in get_model
    return FlashLlamaSharded(model_id, revision, quantize=quantize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 187, in __init__
    self.model = model.eval().to(device)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
 rank=2
2023-04-29T08:27:17.819986Z ERROR shard-manager: text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 58, in serve
    server.serve(model_id, revision, sharded, quantize, uds_path)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 155, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize))
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 124, in serve_inner
    model = get_model(model_id, revision, sharded, quantize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 133, in get_model
    return FlashLlamaSharded(model_id, revision, quantize=quantize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 187, in __init__
    self.model = model.eval().to(device)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
 rank=1
2023-04-29T08:27:17.820004Z ERROR shard-manager: text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 58, in serve
    server.serve(model_id, revision, sharded, quantize, uds_path)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 155, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize))
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 124, in serve_inner
    model = get_model(model_id, revision, sharded, quantize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 133, in get_model
    return FlashLlamaSharded(model_id, revision, quantize=quantize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 187, in __init__
    self.model = model.eval().to(device)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
 rank=0
2023-04-29T08:27:18.628521Z ERROR text_generation_launcher: Shard 2 failed to start:
[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:29500 (errno: 99 - Cannot assign requested address).
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 58, in serve
    server.serve(model_id, revision, sharded, quantize, uds_path)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 155, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize))

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 124, in serve_inner
    model = get_model(model_id, revision, sharded, quantize)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 133, in get_model
    return FlashLlamaSharded(model_id, revision, quantize=quantize)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py", line 187, in __init__
    self.model = model.eval().to(device)

  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)

  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)

  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)

  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)

  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

NotImplementedError: Cannot copy out of meta tensor; no data!


2023-04-29T08:27:18.628569Z  INFO text_generation_launcher: Shutting down shards
2023-04-29T08:27:18.694642Z  INFO text_generation_launcher: Shard 3 terminated
2023-04-29T08:27:18.859049Z  INFO text_generation_launcher: Shard 1 terminated
Error: ShardCannotStart
````

When I run with `--num-shard 1` I get a CUDA OOM error

**Comment by pandazki** [comment]
I also encountered the same problem. However, it's interesting that everything works fine when I use the model from [decapoda-research/llama-7b-hf](https://huggingface.co/decapoda-research/llama-7b-hf), but when I use the same model converted with the [official example](https://huggingface.co/docs/transformers/main/en/model_doc/llama), the above error occurs.

**Comment by SupreethRao99** [comment]
@pandazki  there was an update in the transformers conversion script that fixed the tokenizer and made a few other changes, that could have caused this issues. IIRC deepcoda-research/llama-7b-hf seems to be converted using v1 of conversion script

**Comment by OlivierDehaene** [comment]
@SupreethRao99 Could you stop tagging us? Thank you!

I will have a look at these conversion issues. Thanks for the investigation, very valuable! 
It seems that all the model we serve atm use the old layout so I was not aware of the problem.

**Comment by pai4451** [comment]
> @pandazki there was an update in the transformers conversion script that fixed the tokenizer and made a few other changes, that could have caused this issues. IIRC deepcoda-research/llama-7b-hf seems to be converted using v1 of conversion script
> 
> EDIT: The Inference server only works with models that used the old conversion script. I tried with a version of LLaMA that I converted with the old script and it worked.
> 
> Tagging @OlivierDehaene @njhill @Narsil
> 
> Thank You!

@SupreethRao99 Can you share your conversion script? Which version of the conversation script is compatible with this inference server for LLaMA?

**Comment by Narsil** [comment]
This tokenizer should work : 

```python
tokenizer = AutoTokenizer.from_pretrained("hf-internal-testing/llama-tokenizer")
```

Not sure what you're talking about conversion script.

```python
tokenizer = LlamaTokenizerFast.from_pretrained("hf-internal-testing/llama-tokenizer", from_slow=True)
```

Works (it's slow) and produces the same file. (Make sure you're on latest transformers)

**Comment by SupreethRao99** [comment]
@Narsil I was referring to different version of this file https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py ,  there's a fix to the tokenizer on 3rd April 2023. The models converted with the script before 3rd April work with the current TGI docker containers, the ones converted after don't seem to work with TGI

**Comment by Narsil** [comment]
This is about the weights, not the tokenizer.

Stop pinging people all the time please, we're in the conversation already.
And please make an effort to explain a bit more your issue.

We're making effort to solve your issue proportional to your effort put in explaining the problem.

**Comment by SupreethRao99** [comment]
sorry for the confusion and the pinging, What I meant to say is that using the weights converted using the version of the conversion script after 3rd April 2023 doesn't work with the current implementation of TGI while the weights converted with the older version of the script works. I might have wrongly referenced the tokenizer as I recall seeing the tokenizer changing its BOS and EOS tokens from `""` to `<s>` and `<\s>`.

**Comment by Narsil** [comment]
Is there anything we can do to reproduce the issue ?

**Comment by SupreethRao99** [comment]
yes, I'm trying to deploy vicuna-13b, first I applied the delta and got the vicuna weights in HuggingFace format using this script 
```
python3 -m fastchat.model.apply_delta \
    --base-model-path /path/to/llama-13b \
    --target-model-path /output/path/to/vicuna-13b \
    --delta-path lmsys/vicuna-13b-delta-v1.1
```
(https://github.com/lm-sys/FastChat/blob/main/fastchat/model/apply_delta.py)

The converted model works with `AutoModel.from_pretrained()` and I'm able to run inference.

I then ran 
```
docker run --gpus all --shm-size 1g -p 0.0.0.0:8000:80 -v /home/vicuna-13b:/data ghcr.io/huggingface/text-generation-inference:latest --model-id /data/vicuna-13b --num-shard 4
```

**Comment by Narsil** [comment]
> got the vicuna weights in HuggingFace format

Where ? Which ones ?

**Comment by SupreethRao99** [comment]
the script
```
python3 -m fastchat.model.apply_delta \
    --base-model-path /path/to/llama-13b \
    --target-model-path /output/path/to/vicuna-13b \
    --delta-path lmsys/vicuna-13b-delta-v1.1
``` 
converts LLaMA weights that was downloaded from Meta into a format that can be consumed by AutoModel, 

```
config.json
generation_config.json
pytorch_model-00001-of-00003.bin
pytorch_model-00002-of-00003.bin
pytorch_model-00003-of-00003.bin
pytorch_model.bin.index.json
special_tokens_map.json
tokenizer_config.json
tokenizer.model
```

**Comment by Narsil** [comment]
Anyway you could share those converted weights on the hub ?

**Comment by SupreethRao99** [comment]
sure, the weights can be found here (https://huggingface.co/Supreeth/vicuna-13b)

**Comment by breadbread1984** [comment]
the benchmark tool text-generation-benchmark cannot read tokenizer.model of vicuna 13b. is there any hacking tricks I can use to get it run?

**Comment by Narsil** [comment]
Transform into `tokenizer.json`>

`AutoTokenizer.from_pretrained("xxx").save_pretrained('yyy")`.

`tokenizer.model` is never read, it's a sentencpiece model (insufficient  to run tokenization without the `transformers` python code, which we'd like to avoid rewriting).
