### ISSUE TITLE
VRAM no releasing

### ISSUE THREAD

**Issue by bloodsucker99** [huggingface/text-generation-inference#769]
Hello,

After updating to the newer versions recently, This issue is back: https://github.com/huggingface/text-generation-inference/issues/610. I have tried setting the --cuda-memory-fraction which tbh is not too much of help as before i was able to sit at 11gb each gpu (4) and do 16000 tokens and now im using .75 which does 10000 batch tokens but takes 13gb each model. Further, with each questions asked the vram gets filled till it crashes. This whole new change to auto max batch tokens has really effected everything. 

I was cherry-picking the commits to skip the auto-max-batch token change as it works perfectly without that commit but I can't cherry-pic anymore due to conflicts.  I would love the new updates but it's impossible to use it in this manner as the 13b model is starting at 13gb vram (10000 batch tokens) and vram constantly goes up to 90gb within 10 inferences (~1k+ tokens) and OOM's which did not happen after the cache release on stop update which you can see on the issue I linked before.

Hope to see some fixes upon this or some guidance.

Thanks!

**Comment by Narsil** [comment]
Do you mind sharing a bit more about your environment.

There's a template for the issue that might be helpful to give us a bit more information about what you're trying to do.

Which model and which hardware in particular. (But really try to fill everything it really helps us narrow it down)

**Comment by bloodsucker99** [comment]
Hey @Narsil, I linked the other issue in the first line above. If you check that, my whole hardware is listed there and the issue is pretty much the same. 

I am building the image locally cloning the repo on the latest version as of now. 

docker run --gpus all --shm-size 40g -p 1000:80 -v $volume:/data hug:lat --model-id Oniichat/dolphin-superhot-8k --num-shard 4 --trust-remote-code --max-input-length 4096 --max-total-tokens 10000 --cuda-memory-fraction 0.75

I have also noticed with the whole automaxbatchtoken thing, I am unable to even run some models which i can without that update due to OOM's.

HW Details:

Amazon Linux EC2 g4.12x (4 NVIDIA A10G's 96gb VRAM)

Everything works great if I just skip the automaxbatchtoken commit as well as the kv cache and the other memory commit that goes along with this but as I mentioned, I am unable to keep cherry-picking due to conflictions and manually solving those are pain :(

**Comment by Narsil** [comment]
> automaxbatchtoken

Are you tweaking your settings to make it fit ?
This PR will front load OOM issues before you encounter them in production. Every model needs a bit of tweaking to find a sweet spot on particular hardware.

Are the OOM issues happening during warmup (which is perfectly normal, it means the settings are too high and you need to reduce some of them), or AFTER warmup (which is never supposed to happen thanks to the autobatch).

I checked the model, you could probably drop `trust-remote-code` since it's a llama model, meaning you should have Flash + PagedAttention (could you confirm with the initial logs from the container?).
If those are not active for instance, the max RAM usage will jump through the roof and leading to warmup OOM much earlier than expected.

For the other issue It's easier to track in another one since the error looks different (just refer either issue for the env, sorry for missing it, I read your issue too fast)

**Comment by bloodsucker99** [comment]
I am not OOM'ing while warmup. The warmup is completed which also has issues. So if i dont use --memory thing, it uses 18gb/GPU which is insane so im using .75. Once the model is running and im inferencing with it, the vram just keeps going up and up until it reaches the maximum on the GPU's and OOM's. This was happening before as well if you look at the ticket I linked above and was fixed by adding cache collection when the request is stopped. Seems like there is something new added and now its not clearing the cache like before.

**Comment by Narsil** [comment]
We removed the torch `cudaAllocAsync` which was indeed causing lots of issues. That was fixed in `0.9.4`

Not sure you shared your version of the program. If running  `:lastest` did you add `--pull always` ? 

I'm running the same settings as you, after warmup all GPUS are at 12GB or RAM (it shouldn't actually matter that much anyway, because torch allocator will do a lot of things, so nvidia-smi != actual RAM usage.

I'm using using the same settings as you, and getting `Setting max batch total tokens to 26464` which seems higher than the 16k you had before. Could you share all your logs maybe there's something going wrong in your env ?

Also `shm 40g` might be a bit overboard (shouldn't cause issues, but it shouldn't be necessary to put that much)

**Comment by bloodsucker99** [comment]
Regarding the version, I am actually cloning the repo and ensuring git pull and building the docker image myself using:
docker build . -t hug:lat

Now regarding 12gb for you, that is very odd because if I do not set the .75 value, my gpu's are sitting at 18gb each after the warmup. Once the warmup completes, it's not releasing that cache. I am using nvitop and it is crucial for the system to know that there is available ram because I am running 2 other models on the machine. If I use the older build without maxauto, I am comfortably running all 3 models (1 13b hf, 1 15b gptq, SD) while sitting at 16.5gb on all GPU's. Both 13b and 15b models using 16k batch-tokens but now I can barely run one unless I use .75 (if I leave default 1.0, it sits at 18gb all 4 gpu's after the warmup) and on top of it, the ram just keeps flowing with each inference (Only im inferencing with it and it takes like 10 queries and OOM's). I have tried to delete the whole folder and re cloned it twice now and freshly creating the docker image (cleaning up all the old ones and even using a new name) but still getting the same results.

**Comment by bloodsucker99** [comment]
these first 2 images show how its keep filling the vram when I only have 1 model running. its a 33b model
![image](https://github.com/huggingface/text-generation-inference/assets/57774784/b5e93358-9f39-42d6-833f-94fb8839f3cd)

![image](https://github.com/huggingface/text-generation-inference/assets/57774784/7efff0c0-cad3-4abc-8c9d-2e5a66e05bd2)

Now this image shows when it finishes loading the model and starts warmup process. Now this is where thins go wrong. So before when it does the warmup, it will go back to the loaded vram so lets say my model starts at 8gb/gpu, it will do a warmup and say goes upto 16gb/each, once the warmup finishes, it goes back to 8gb/each.
![image](https://github.com/huggingface/text-generation-inference/assets/57774784/0dae1edf-751f-4a0b-a96b-c0ce1e74ea3b)

Now look into this image where the model is not returning back to its loaded vram usage but instead stuck at the max of warmup and starts from there. Now when I make the request it adds upon this the vram until it hits the maximum which is what my concern is.
![image](https://github.com/huggingface/text-generation-inference/assets/57774784/f9214a37-3152-42a6-bfc1-b324f681ecbd)

After that little cache collector patch from the other ticket, things were perfect but now its happening again sadly.

**Comment by bloodsucker99** [comment]
Hey @Narsil Had a chance to look through?

**Comment by bloodsucker99** [comment]
So i have actually fixed the vram reset myself. Seems like the new updates removed the fix Oliver created last time so i just added back that fix manually and it works :) I will close this soon after I messs with it a little bit more

**Comment by Narsil** [comment]
Do you mind sharing what you are talking about ?

the "fixes" (`torch.cuda.clear_cache()` ) are not necessary anymore.

**Comment by bloodsucker99** [comment]
@Narsil Well it seems to fix the problem though. I added it again where it stops and it works.

However the models take bit more vram now than before while using less batch tokens so thats still a thing.

Also as of current state, wizardcoder or santacoder models are producing random characters which did not happen before. Something seems to be wrong regarding santacoder models.
