### ISSUE TITLE
max batch total tokens problem

### ISSUE THREAD

**Issue by jiangix-paper** [huggingface/text-generation-inference#832]
### System Info

text-generation-inference version: 1.0

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

I use 4*80G A100 to launcher the llama2-70b, it has the information: Setting max batch total tokens to 406560
![image](https://github.com/huggingface/text-generation-inference/assets/62198809/738e451c-22eb-4b60-bfe6-0ba91ded7bf8)
If the max-total-tokens is 4096, I think the batch size is 406560/4096=99.
But when I test it using text-generation-benchmark, I only set batch size=32, and it has cuda out of memoy.

### Expected behavior

solve the problem of cuda out of memory

**Comment by sjzhou4** [comment]
i met same
![image](https://github.com/huggingface/text-generation-inference/assets/142190228/aabcde0c-f844-4bf1-83f7-09397b63e8f0)

**Comment by maziyarpanahi** [comment]
The new `1.0.1` image with the same old flags also causes excessive memory usage suddenly:

```
2023-08-22T17:48:37.505854Z  INFO text_generation_launcher: Args { model_id: "meta-llama/Llama-2-13b-chat-hf", revision: None, validation_workers: 2, sharded: None, num_shard: Some(4), quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_st
op_sequences: 4, max_input_length: 4096, max_total_tokens: 8192, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "e3c0c2cc1223", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", maste
r_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ng
rok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-08-22T17:48:37.505882Z  INFO text_generation_launcher: Sharding model on 4 processes
2023-08-22T17:48:37.505981Z  INFO download: text_generation_launcher: Starting download process.
2023-08-22T17:48:41.519577Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-08-22T17:48:42.109526Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-08-22T17:48:42.109834Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-08-22T17:48:42.109910Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-08-22T17:48:42.110558Z  INFO shard-manager: text_generation_launcher: Starting shard rank=3
2023-08-22T17:48:42.110565Z  INFO shard-manager: text_generation_launcher: Starting shard rank=2
2023-08-22T17:48:52.117293Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-22T17:48:52.117805Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=1
2023-08-22T17:48:52.118175Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=2
2023-08-22T17:48:52.118316Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=3
2023-08-22T17:48:55.958802Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-3

2023-08-22T17:48:56.021360Z  INFO shard-manager: text_generation_launcher: Shard ready in 13.90970234s rank=3
2023-08-22T17:48:56.057510Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-08-22T17:48:56.072159Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-1

2023-08-22T17:48:56.074311Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-2

2023-08-22T17:48:56.120909Z  INFO shard-manager: text_generation_launcher: Shard ready in 14.009652831s rank=1
2023-08-22T17:48:56.121430Z  INFO shard-manager: text_generation_launcher: Shard ready in 14.010060624s rank=2
2023-08-22T17:48:56.123510Z  INFO shard-manager: text_generation_launcher: Shard ready in 14.012808255s rank=0
2023-08-22T17:48:56.218943Z  INFO text_generation_launcher: Starting Webserver
2023-08-22T17:48:56.794558Z  WARN text_generation_router: router/src/main.rs:345: `--revision` is not set
2023-08-22T17:48:56.794580Z  WARN text_generation_router: router/src/main.rs:346: We strongly advise to set it to a known supported commit.
2023-08-22T17:48:57.013516Z  INFO text_generation_router: router/src/main.rs:367: Serving revision 0ba94ac9b9e1d5a0037780667e8b219adde1908c of model meta-llama/Llama-2-13b-chat-hf
2023-08-22T17:48:57.018593Z  INFO text_generation_router: router/src/main.rs:210: Warming up model
2023-08-22T17:49:00.883050Z  INFO text_generation_router: router/src/main.rs:243: Setting max batch total tokens to 347776
2023-08-22T17:49:00.883068Z  INFO text_generation_router: router/src/main.rs:244: Connected
2023-08-22T17:49:00.883074Z  WARN text_generation_router: router/src/main.rs:249: Invalid hostname, defaulting to 0.0.0.0
```

The shard is 4 and `--max-total-tokens 8192` ` --max-input-length 4096` - the same docker run works perfectly with `0.9.3` with 27G to 30G usage in total across all 4 GPUs. In `1.0.1` it doesn't crash because I have 320G in total GPU memory.

I think in the newer versions there is a default number somewhere or I should set something to avoid this `Setting max batch total tokens to 347776` as it explodes right after printing this line.

**Comment by maziyarpanahi** [comment]
I would like to correct myself, it seems to be an issue starting `0.9.4`. I will live a end-to-end example here:

The cli command to run the docker for `0.9.3` and `0.9.4` with identical flags which is a different between 4x 11300MiB vs. 4x 76020MiB. I believe something happened here to rather simplify setting these max tokens that either doesn't work on all ENVs models, or I am missing something to set with a very low number: https://github.com/huggingface/text-generation-inference/pull/630

With `0.9.3`:

```sh
docker run \
  --name "${NAME}" \
  --gpus all \
  --shm-size 2g \
  -p $PORT:80 \
  -e HUGGING_FACE_HUB_TOKEN= \
  -v $volume:/data \
  --detach \
  ghcr.io/huggingface/text-generation-inference:0.9.3 \
  --model-id $model_id \
  --num-shard $num_shard \
  --max-total-tokens 8192 \
  --max-input-length 4096
```


```
2023-08-22T18:35:50.966384Z  INFO text_generation_launcher: Args { model_id: "meta-llama/Llama-2-13b-chat-hf", revision: None, validation_workers: 2, sharded: None, num_shard: Some(4), quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 4096, max_total_tokens: 8192, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: 16000, max_waiting_tokens: 20, hostname: "831e9d857f4c", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_domain: None, ngrok_username: None, ngrok_password: None, env: false }
2023-08-22T18:35:50.966415Z  INFO text_generation_launcher: Sharding model on 4 processes
2023-08-22T18:35:50.966517Z  INFO download: text_generation_launcher: Starting download process.
2023-08-22T18:35:53.722427Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-08-22T18:35:54.569514Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-08-22T18:35:54.569821Z  INFO shard-manager: text_generation_launcher: Starting shard 0 rank=0
2023-08-22T18:35:54.569846Z  INFO shard-manager: text_generation_launcher: Starting shard 1 rank=1
2023-08-22T18:35:54.570439Z  INFO shard-manager: text_generation_launcher: Starting shard 2 rank=2
2023-08-22T18:35:54.570524Z  INFO shard-manager: text_generation_launcher: Starting shard 3 rank=3
2023-08-22T18:36:04.577792Z  INFO shard-manager: text_generation_launcher: Waiting for shard 0 to be ready... rank=0
2023-08-22T18:36:04.577877Z  INFO shard-manager: text_generation_launcher: Waiting for shard 1 to be ready... rank=1
2023-08-22T18:36:04.577948Z  INFO shard-manager: text_generation_launcher: Waiting for shard 2 to be ready... rank=2
2023-08-22T18:36:04.578348Z  INFO shard-manager: text_generation_launcher: Waiting for shard 3 to be ready... rank=3
2023-08-22T18:36:08.252380Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-3

2023-08-22T18:36:08.280330Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-1

2023-08-22T18:36:08.280869Z  INFO shard-manager: text_generation_launcher: Shard 1 ready in 13.709866754s rank=1
2023-08-22T18:36:08.281223Z  INFO shard-manager: text_generation_launcher: Shard 3 ready in 13.70945285s rank=3
2023-08-22T18:36:08.302626Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-2

2023-08-22T18:36:08.329096Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-08-22T18:36:08.380896Z  INFO shard-manager: text_generation_launcher: Shard 2 ready in 13.809521206s rank=2
2023-08-22T18:36:08.380927Z  INFO shard-manager: text_generation_launcher: Shard 0 ready in 13.810307918s rank=0
2023-08-22T18:36:08.478732Z  INFO text_generation_launcher: Starting Webserver
2023-08-22T18:36:09.208451Z  WARN text_generation_router: router/src/main.rs:324: `--revision` is not set
2023-08-22T18:36:09.208471Z  WARN text_generation_router: router/src/main.rs:325: We strongly advise to set it to a known supported commit.
2023-08-22T18:36:09.643493Z  INFO text_generation_router: router/src/main.rs:346: Serving revision 0ba94ac9b9e1d5a0037780667e8b219adde1908c of model meta-llama/Llama-2-13b-chat-hf
2023-08-22T18:36:09.649716Z  INFO text_generation_router: router/src/main.rs:212: Warming up model
2023-08-22T18:36:13.272971Z  INFO text_generation_router: router/src/main.rs:221: Connected
2023-08-22T18:36:13.272993Z  WARN text_generation_router: router/src/main.rs:226: Invalid hostname, defaulting to 0.0.0.0

Tue Aug 22 18:36:46 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe           On | 00000000:08:00.0 Off |                    0 |
| N/A   38C    P0               67W / 300W|  11302MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe           On | 00000000:48:00.0 Off |                    0 |
| N/A   36C    P0               63W / 300W|  11310MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100 80GB PCIe           On | 00000000:88:00.0 Off |                    0 |
| N/A   36C    P0               64W / 300W|  11310MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100 80GB PCIe           On | 00000000:C8:00.0 Off |                    0 |
| N/A   36C    P0               63W / 300W|  11270MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   1972012      C   /opt/conda/bin/python3.9                  11300MiB |
|    1   N/A  N/A   1972013      C   /opt/conda/bin/python3.9                  11308MiB |
|    2   N/A  N/A   1972015      C   /opt/conda/bin/python3.9                  11308MiB |
|    3   N/A  N/A   1972017      C   /opt/conda/bin/python3.9                  11268MiB |
+---------------------------------------------------------------------------------------+
```


With `0.9.4`:

```sh
docker run \
  --name "${NAME}" \
  --gpus all \
  --shm-size 2g \
  -p $PORT:80 \
  -e HUGGING_FACE_HUB_TOKEN= \
  -v $volume:/data \
  --detach \
  ghcr.io/huggingface/text-generation-inference:0.9.4 \
  --model-id $model_id \
  --num-shard $num_shard \
  --max-total-tokens 8192 \
  --max-input-length 4096
```

```
2023-08-22T18:32:21.740739Z  INFO text_generation_launcher: Args { model_id: "meta-llama/Llama-2-13b-chat-hf", revision: None, validation_workers: 2, sharded: None, num_shard: Some(4), quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 4096, max_total_tokens: 8192, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "0da69a223a58", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-08-22T18:32:21.740761Z  INFO text_generation_launcher: Sharding model on 4 processes
2023-08-22T18:32:21.740855Z  INFO download: text_generation_launcher: Starting download process.
2023-08-22T18:32:24.992696Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-08-22T18:32:25.744129Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-08-22T18:32:25.744846Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-08-22T18:32:25.744847Z  INFO shard-manager: text_generation_launcher: Starting shard rank=3
2023-08-22T18:32:25.744848Z  INFO shard-manager: text_generation_launcher: Starting shard rank=2
2023-08-22T18:32:25.744850Z  INFO shard-manager: text_generation_launcher: Starting shard rank=1
2023-08-22T18:32:35.752342Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=3
2023-08-22T18:32:35.752431Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=2
2023-08-22T18:32:35.752475Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-22T18:32:35.752759Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=1
2023-08-22T18:32:40.814730Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-3

2023-08-22T18:32:40.845352Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-1

2023-08-22T18:32:40.856124Z  INFO shard-manager: text_generation_launcher: Shard ready in 15.110481277s rank=3
2023-08-22T18:32:40.858248Z  INFO shard-manager: text_generation_launcher: Shard ready in 15.111926233s rank=1
2023-08-22T18:32:40.861504Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-2

2023-08-22T18:32:40.890708Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-08-22T18:32:40.956214Z  INFO shard-manager: text_generation_launcher: Shard ready in 15.210237629s rank=0
2023-08-22T18:32:40.956394Z  INFO shard-manager: text_generation_launcher: Shard ready in 15.210305294s rank=2
2023-08-22T18:32:40.958132Z  INFO text_generation_launcher: Starting Webserver
2023-08-22T18:32:41.406346Z  WARN text_generation_router: router/src/main.rs:341: `--revision` is not set
2023-08-22T18:32:41.406362Z  WARN text_generation_router: router/src/main.rs:342: We strongly advise to set it to a known supported commit.
2023-08-22T18:32:41.641062Z  INFO text_generation_router: router/src/main.rs:363: Serving revision 0ba94ac9b9e1d5a0037780667e8b219adde1908c of model meta-llama/Llama-2-13b-chat-hf
2023-08-22T18:32:41.651831Z  INFO text_generation_router: router/src/main.rs:210: Warming up model
2023-08-22T18:32:45.602566Z  INFO text_generation_router: router/src/main.rs:239: Setting max batch total tokens to 348160
2023-08-22T18:32:45.602596Z  INFO text_generation_router: router/src/main.rs:240: Connected
2023-08-22T18:32:45.602606Z  WARN text_generation_router: router/src/main.rs:245: Invalid hostname, defaulting to 0.0.0.0

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe           On | 00000000:08:00.0 Off |                    0 |
| N/A   38C    P0               67W / 300W|  76172MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe           On | 00000000:48:00.0 Off |                    0 |
| N/A   37C    P0               63W / 300W|  76180MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100 80GB PCIe           On | 00000000:88:00.0 Off |                    0 |
| N/A   37C    P0               64W / 300W|  76020MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100 80GB PCIe           On | 00000000:C8:00.0 Off |                    0 |
| N/A   37C    P0               64W / 300W|  76460MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   1968614      C   /opt/conda/bin/python3.9                  76170MiB |
|    1   N/A  N/A   1968617      C   /opt/conda/bin/python3.9                  76178MiB |
|    2   N/A  N/A   1968615      C   /opt/conda/bin/python3.9                  76018MiB |
|    3   N/A  N/A   1968613      C   /opt/conda/bin/python3.9                  76458MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by Narsil** [comment]
There's nothing wrong. After 0.9.4 we're warming up the RAM to prevent explosion during runtime (when you receive enough load).

If you don't want to use all the VRAM you can use `--cuda-memory-fraction`.

**Comment by maziyarpanahi** [comment]
@Narsil 
Before 0.9.4 release, I was stress-testing the system by concurrent users and max token lengths. I didn't noticed GPU memory exploding to 7x times. 

I don't think there is something wrong, I think there is a flag missing from my docker run to somehow ground the VRAM to a specific amount like before

**Comment by Narsil** [comment]
>  didn't noticed GPU memory exploding to 7x times.

The warmup assumes worse possible conditions which are max batch size + max PREFILL step :).
Since we've added that we haven't seen any OOM in production anymore, which was happening before on actually stressed models.

Closing since issue seems to be solved.

**Comment by maziyarpanahi** [comment]
> The warmup assumes worse possible conditions which are max batch size + max PREFILL step :).
> Since we've added that we haven't seen any OOM in production anymore, which was happening before on actually stressed models.

Totally makes sense, thanks for this new feature.
