### ISSUE TITLE
Out of memory error running on a a T4, even for quantized models

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/text-generation-inference#856]
### System Info

I'm running an Ubuntu 22.04 instance with a T4 GPU with 16 GB of VRAM.
```
 NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2  
```
I'm using docker:
```
docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.1 --model-id $model --max-batch-prefill-tokens 256 --max-input-length 256
```
I'm running python 3.9 and have installed the NVidia container toolkit and updated to the latest cuda (see above, 12.2).

The models I am loading are either (in bfloat16 size):
-13 GB
-8 GB.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

I have tested various scenarios, first a gptq quantized model (~3 GB in size):
```
model=Trelis/Llama-2-7b-chat-hf-function-calling-GPTQ
```
with the '--quantize gptq' flag, which gives:
```
RuntimeError: Not enough memory to handle 256 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
```
~~~
I also tried an 8-bit model (~8 GB in size):
```
model=Trelis/Llama-2-7b-chat-hf-hosted-inference-8bit
```
with the '--dtype bfloat16' flag, which gives the same error of not enough memory.
~~~
I also tried to load a 13 GB model with:
```
model=Trelis/Llama-2-7b-chat-hf-function-calling
```
with no quantization or dtype flags, yielding:
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.00 MiB (GPU 0; 14.58 GiB total capacity; 14.33 GiB already allocated; 23.56 MiB free; 14.58 GiB allowed; 14.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
which probably makes sense because I assume this would be loaded in float32, which would make it too big. So I added the '--dtype bfloat16' flag, which resulted in many lines of:
```
2023-08-16T11:06:47.847617Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-16T11:06:57.856146Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
```
followed by:
```
RuntimeError: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
```

Some other errors that seemed relevant:

```
Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2
```
and
```
You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
```

### Expected behavior

I would expect the 8bit model to run, and also the gptq model. I'm unsure whether the 13B model in bfloat would run - it may be too tight on memory.

**Comment by Narsil** [comment]
Can you provide the full logs ?


Sometimes the error is not actually OOM at startup but something else, and we erroneously detect it as OOM.
It should still be clearer when rolling up the logs.

Indeed everything should work on said hardware + model.

**Comment by RonanKMcGovern** [comment]
Appreciate the help!

I'm running on a g4dn.2xlarge, which has one 16 GB VRAM T4 GPU.

Here are my [install scripts](https://github.com/TrelisResearch/gpu-install-on-ec2).

Full logs:
```
ubuntu@ip-172-31-39-33:~$ model=Trelis/Llama-2-7b-chat-hf-hosted-inference-8bit
ubuntu@ip-172-31-39-33:~$ volume=$PWD/data
ubuntu@ip-172-31-39-33:~$ docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.1 --model-id $model --dtype bfloat16
2023-08-17T10:47:36.256664Z  INFO text_generation_launcher: Args { model_id: "Trelis/Llama-2-7b-chat-hf-hosted-inference-8bit", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: Some(BFloat16), trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "6997a382eedf", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-08-17T10:47:36.256828Z  INFO download: text_generation_launcher: Starting download process.
2023-08-17T10:47:43.869938Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-08-17T10:47:44.965438Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-08-17T10:47:44.965675Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-08-17T10:47:48.126049Z  WARN text_generation_launcher: Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2

2023-08-17T10:47:54.973049Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-17T10:48:04.979890Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-17T10:48:14.987038Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-17T10:48:24.993740Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-17T10:48:35.001335Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-17T10:48:40.617020Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0

2023-08-17T10:48:40.705684Z  INFO shard-manager: text_generation_launcher: Shard ready in 55.739385475s rank=0
2023-08-17T10:48:40.803038Z  INFO text_generation_launcher: Starting Webserver
2023-08-17T10:48:41.598729Z  WARN text_generation_router: router/src/main.rs:345: `--revision` is not set
2023-08-17T10:48:41.598754Z  WARN text_generation_router: router/src/main.rs:346: We strongly advise to set it to a known supported commit.
2023-08-17T10:48:41.732173Z  INFO text_generation_router: router/src/main.rs:367: Serving revision 0b6cac684d4fed413355c540b80e8309ec1553c9 of model Trelis/Llama-2-7b-chat-hf-hosted-inference-8bit
2023-08-17T10:48:41.746564Z  INFO text_generation_router: router/src/main.rs:210: Warming up model
2023-08-17T10:48:41.873487Z ERROR text_generation_launcher: Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 719, in warmup
    CACHE_MANAGER = CacheManager(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 47, in __init__
    self.kv_cache = [
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 49, in <listcomp>
    torch.empty(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.00 MiB (GPU 0; 14.58 GiB total capacity; 14.33 GiB already allocated; 23.56 MiB free; 14.58 GiB allowed; 14.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 184, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 60, in Warmup
    max_supported_total_tokens = self.model.warmup(batch)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_causal_lm.py", line 729, in warmup
    raise RuntimeError(
RuntimeError: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`

2023-08-17T10:48:41.939712Z ERROR warmup{max_input_length=1024 max_prefill_tokens=4096}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
Error: Warmup(Generation("Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`"))
2023-08-17T10:48:42.006878Z ERROR text_generation_launcher: Webserver Crashed
2023-08-17T10:48:42.006905Z  INFO text_generation_launcher: Shutting down shards
2023-08-17T10:48:42.287498Z  INFO shard-manager: text_generation_launcher: Shard terminated rank=0
Error: WebserverFailed
```

**Comment by RonanKMcGovern** [comment]
@Narsil , are the above logs helpful in identifying a potential issue? Thanks

**Comment by Narsil** [comment]
Yes, you are not using 8bit quantization here you need to add `--quantize bitsandbytes` if you want 8bit quantization (`bitsandbytes-nf4`, `bitsandbytes-fp4` for 4 bit).

8bit is only in the name of the model.

**Comment by RonanKMcGovern** [comment]
Thanks @Narsil , many thanks. That solved the issue on the textgen side.

The 8bit model ran (although it produced <unk> tokens).

The Trelis/Llama-2-7b-chat-hf-function-calling (which is a full precision model) ran in --quantize Trelis/Llama-2-7b-chat-hf-function-calling and it gave sensible tokens.

So perhaps there's an issue with how I'm loading the 8bit model, but fixing my flags omission addressed the issue. Thanks
